import { Suspense } from "react";
import { Metadata } from "next";
import ControlsContent from "./_components/controls-content";
import ControlsHeader from "./_components/controls-header";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "제어 항목 관리",
  description: "Generated by create next app",
};

export default async function Page({
  searchParams,
}: {
  searchParams: { [key: string]: string };
}) {
  const { page } = await searchParams;

  return (
    <>
      <ControlsHeader />
      <Suspense key={page} fallback={<Loading />}>
        <ControlsContent searchParams={searchParams} />
      </Suspense>
    </>
  );
}
