type Rule = {
  id: string;
  name: string;
  description: string;
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  status: "enabled" | "disabled";
  lastModified: string;
  notifications: string[];
};

export const mockRules: Rule[] = [
  {
    id: "1",
    name: "High Severity Alert for EC2 Instances",
    description: "Alerts on high severity findings in EC2 instances.",
    severity: "HIGH",
    status: "enabled",
    lastModified: "2023-10-15T12:34:56Z",
    notifications: ["Jira", "Slack"],
  },
  {
    id: "2",
    name: "Medium Severity Alert for S3 Buckets",
    description: "Alerts on medium severity findings in S3 Buckets.",
    severity: "MEDIUM",
    status: "disabled",
    lastModified: "2023-09-10T08:22:34Z",
    notifications: ["Slack"],
  },
  {
    id: "3",
    name: "Low Severity Alert for Lambda Functions",
    description: "Alerts on low severity findings in Lambda functions.",
    severity: "LOW",
    status: "enabled",
    lastModified: "2023-11-01T14:21:10Z",
    notifications: ["Jira"],
  },
  {
    id: "4",
    name: "Critical Alert for RDS Instances",
    description: "Critical alert for unauthorized access in RDS instances.",
    severity: "CRITICAL",
    status: "enabled",
    lastModified: "2023-08-25T10:30:45Z",
    notifications: ["Slack", "Email"],
  },
  {
    id: "5",
    name: "Unauthorized Access Alert for S3 Buckets",
    description: "Detects unauthorized access to S3 Buckets.",
    severity: "HIGH",
    status: "enabled",
    lastModified: "2023-07-20T09:11:29Z",
    notifications: ["Jira", "Email"],
  },
  {
    id: "6",
    name: "EC2 Instance Data Leak Alert",
    description: "Detects potential data leaks from EC2 instances.",
    severity: "HIGH",
    status: "disabled",
    lastModified: "2023-09-18T13:55:34Z",
    notifications: ["Slack"],
  },
  {
    id: "7",
    name: "IAM User Policy Change Alert",
    description: "Alerts on changes to IAM user policies.",
    severity: "MEDIUM",
    status: "enabled",
    lastModified: "2023-08-03T17:42:10Z",
    notifications: ["Jira", "Slack"],
  },
  {
    id: "8",
    name: "High CPU Usage Alert for EC2",
    description: "Alerts when EC2 CPU usage exceeds threshold.",
    severity: "HIGH",
    status: "enabled",
    lastModified: "2023-06-22T11:13:20Z",
    notifications: ["Slack", "Email"],
  },
  {
    id: "9",
    name: "Exposed IAM Keys Alert",
    description: "Detects exposed IAM access keys in public repositories.",
    severity: "CRITICAL",
    status: "enabled",
    lastModified: "2023-10-01T09:08:42Z",
    notifications: ["Jira", "Slack", "Email"],
  },
  {
    id: "10",
    name: "S3 Bucket Public Access Alert",
    description: "Alerts on public access to S3 buckets.",
    severity: "HIGH",
    status: "enabled",
    lastModified: "2023-05-19T14:54:22Z",
    notifications: ["Slack"],
  },
  {
    id: "11",
    name: "VPC Flow Logs Disabled Alert",
    description: "Detects VPCs without flow logging enabled.",
    severity: "MEDIUM",
    status: "disabled",
    lastModified: "2023-09-27T16:34:15Z",
    notifications: ["Jira"],
  },
  {
    id: "12",
    name: "Root Account Login Alert",
    description: "Alerts on root account login events.",
    severity: "CRITICAL",
    status: "enabled",
    lastModified: "2023-10-11T15:30:01Z",
    notifications: ["Jira", "Slack", "Email"],
  },
  {
    id: "13",
    name: "Insecure Security Group Rules",
    description: "Alerts on security groups with wide open rules.",
    severity: "HIGH",
    status: "enabled",
    lastModified: "2023-06-05T12:14:35Z",
    notifications: ["Jira"],
  },
  {
    id: "14",
    name: "RDS Instance Backup Disabled Alert",
    description: "Detects RDS instances without backups.",
    severity: "HIGH",
    status: "disabled",
    lastModified: "2023-07-12T10:20:55Z",
    notifications: ["Slack"],
  },
  {
    id: "15",
    name: "Weak IAM Password Policy Alert",
    description: "Detects weak IAM password policies.",
    severity: "MEDIUM",
    status: "enabled",
    lastModified: "2023-10-17T12:00:10Z",
    notifications: ["Email"],
  },
  {
    id: "16",
    name: "Overdue Compliance Checks Alert",
    description: "Detects overdue compliance checks for resources.",
    severity: "LOW",
    status: "enabled",
    lastModified: "2023-08-30T08:45:16Z",
    notifications: ["Jira", "Slack"],
  },
  {
    id: "17",
    name: "Suspicious Network Traffic Alert",
    description: "Detects suspicious traffic patterns in network logs.",
    severity: "CRITICAL",
    status: "enabled",
    lastModified: "2023-09-21T11:09:10Z",
    notifications: ["Slack"],
  },
  {
    id: "18",
    name: "Unencrypted S3 Bucket Alert",
    description: "Alerts on unencrypted S3 buckets.",
    severity: "HIGH",
    status: "enabled",
    lastModified: "2023-07-29T13:31:22Z",
    notifications: ["Jira", "Email"],
  },
  {
    id: "19",
    name: "MFA Not Enabled Alert for IAM Users",
    description: "Alerts on IAM users without MFA enabled.",
    severity: "MEDIUM",
    status: "disabled",
    lastModified: "2023-09-08T14:23:18Z",
    notifications: ["Slack"],
  },
  {
    id: "20",
    name: "CloudTrail Disabled Alert",
    description: "Alerts when CloudTrail is disabled in the account.",
    severity: "CRITICAL",
    status: "enabled",
    lastModified: "2023-10-20T12:40:05Z",
    notifications: ["Jira", "Slack"],
  },
];
