import type { Metadata } from "next";
import { GridItem, SimpleGrid } from "@chakra-ui/react";
import RegionSelectSidebar from "./_components/region-select-sidebar";
import RulesList from "./_components/rules-list";
import PageHeading from "../_components/page-heading";

export const metadata: Metadata = {
  title: "알림 규칙 관리",
  description: "Generated by create next app",
};

export default async function Page() {
  const data = await fetch(`${process.env.API_HOST}/count_yaml`);
  const regionalRuleSummaries = await data.json();

  return (
    <>
      <PageHeading>{metadata.title as string}</PageHeading>
      <SimpleGrid columns={{ base: 1, md: 3 }} gap="6">
        <GridItem colSpan={1}>
          <RegionSelectSidebar regionalRuleSummaries={regionalRuleSummaries} />
        </GridItem>
        <GridItem colSpan={{ base: 1, md: 2 }}>
          <RulesList regionalRules={regionalRuleSummaries} />
        </GridItem>
      </SimpleGrid>
    </>
  );
}
