import type { Metadata } from "next";
import PageHeading from "@/app/(protected)/_components/page-heading";
import SecurityOverviewSection from "./_components/security-overview-section";
import SecurityIssueSection from "./_components/security-issue-section";

export const metadata: Metadata = {
  title: "대시보드",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <PageHeading>{metadata.title as string}</PageHeading>
      <SecurityOverviewSection />
      <SecurityIssueSection />
    </>
  );
}
